name: Hello World Image Build

on:
  push:
    tags:
      - 'release-*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: DEPLOY
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2
        with:
          strip_v: false
          default: 0.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/errepinet/hello-world:latest
            ghcr.io/errepinet/hello-world:${{ steps.tag.outputs.tag }}
